baseURL = "http://www.smith3v.com/"
languageCode = "en-us"
title = "Slava @smith3v Kuznetsov"
theme = "hugo-resume"

[params]
    firstName = "Slava"
    lastName = "Kuznetsov"
    address = "Haarlem, Netherlands"
    # phone = "1-555-555-1234"
    contactNote = "SRE Teamlead"
    profileImage = "images/profile.jpg"
    email = "neuron@smith3v.com"
    description = "SRE Teamlead. Ex-Head of IT Operations @ecwid. Program committee member @devoopsconf & @DevOpsConfRus. Proud daddy lvl 2. DevOps follower. Cloud advocate lvl 8. Security addicted lvl 3. Proud daddy lvl 2."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = false
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = false
    showEducation = false

    showQr = true

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/smith3v"

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/smith3v"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/smith3v"

#[[params.handles]]
#    name = "Bitbucket"
#    link = "https://bitbucket.org/smith3v/"

#[[params.handles]]
#    name = "Stack Overflow"
#    link = "https://stackoverflow.com/users/story/82880"
#    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/smith3v"
    icon = "keybase"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/neuron/"

#[params.google.analytics]
#    trackerID = "XX-123446-01"
