name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean build directory
      run: rm -rf public

    - name: Clean cache directory
      run: rm -rf resources

    - name: Checkout
      uses: actions/checkout@v1

    - name: Update theme
      uses: srt32/git-actions@master
      with:
        args: "cd themes && git clone https://github.com/smith3v/hugo-resume.git hugo-resume-smith3v"

    - name: Build pages
      uses: srt32/hugo-action@v0.0.3
      with:
        args: --theme=hugo-resume --ignoreCache

    - name: Publish update
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'www.smith3v.com'
        AWS_ACCESS_KEY_ID: ${{ secrets.YANDEX_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_S3_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ru-central1'
        AWS_S3_ENDPOINT: 'https://storage.yandexcloud.net'
        SOURCE_DIR: 'public'
