name: CI

on:  
  push:
    branches:
    - master
    - smith3v-ci-setup

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Build pages
      uses: srt32/hugo-action@v0.0.3

